### ISSUE TITLE
I can't make source code on windows

### ISSUE THREAD

**Issue by beebrain** [Vastlab/libMR#4]
I try to make libmr source code with cmake 3.12. 
I followed your instruction:
"use CMake GUI
Source code = <where libmr is> libMR/libMR
Where to build binaries = < where libmr is > /libMR/build
Click generate
Select correct visual studio version compiler"

I got some error message. The error message is "CMake Error at CMakeLists.txt:15 (install):
  install Library TARGETS given no DESTINATION! "

I don't know how to fix that problem. Please tell me to fix it.

This is my error picture.
![image](https://user-images.githubusercontent.com/10016227/42374697-2480e832-8143-11e8-8eb6-0cbbe06e44fa.png)

**Comment by zhyhy** [comment]
Hello, I also use Cmake to compile under Windows, but I am too unclear about "Build ALL_BUILD project to build libmr
Build INSTALL project to install
Add install dir to path to link against libmr dll. Can you explain the meaning of these three sentences in detail?

**Comment by zhyhy** [comment]
> Hello,
> 
> I am not familiar with the installation on Windows, but I have tried to address your issue in branch `Windows_Install`. Could you please check out that branch and let me know if this helps?
> 
> Manuel

Hello, I also use Cmake to compile under Windows, but I am too unclear about "Build ALL_BUILD project to build libmr
Build INSTALL project to install
Add install dir to path to link against libmr dll. Can you explain the meaning of these three sentences in detail?

**Comment by siebenkopf** [comment]
From your description, I am not sure what exactly is your problem. If it is an issue with CMake, have you tried to google for it? Try for example: http://docs.microsoft.com/en-us/cpp/build/cmake-projects-in-visual-studio?view=msvc-160

**Comment by lucasteyn** [comment]
@zhyhy I had a similar issue due to MY lack of knowledge on how to compile code in visual studio. Here are my steps that solved the same questions you asked if you are still interested. I’m using Windows 10, CMake 3.20, Visual Studio 2019 with Cpp compilers and Python 3.6 with cython 0.29.21.
1. Make sure you have C++ compilers installed with visual studio. The best is to try and run the “Hello World” example in Visual Studio. If it doesn’t work, make sure to install Visual Studio with the necessary compilers. 
2. Follow the steps in CMake (run as administrator) by specifying the build directory and generate the folder. 
3. Open the Visual Studio (run as administrator) version that you specified in CMake. 
4. Select “Open a local folder”.
5. Browse to the created “build” folder from CMake and click “select folder”. 
6. Go to x64 dir and double click ALL_BUILD.vcxproj.
7. Press ctrl+F5 to run. 
8. Do steps 6 and 7 for the INSTALL.vcxproj
After these steps I ran pip install libmr which worked perfectly. 
Cheers
